## 라이브러리 불러오기

In [ ]:
import pandas as pd
import numpy as np

## 2018년 강수량 데이터

- 시간별 강수량 데이터 불러오기

In [ ]:
df_2018 = pd.read_csv("2018.csv",encoding='cp949')

- 결측치 0으로 채우기

In [ ]:
df_2018["강수량(mm)"] = df_2018["강수량(mm)"].replace(np.nan, 0)

- 필요한 변수 추출

In [ ]:
df_2018.drop(['강수량 QC플래그','지점명','지점'], axis=1,  inplace=True)

- 날짜를 index로 시간을 column으로 pivot table 생성

In [ ]:
splited = df_2018['일시'].str.split(' ', expand=True)
splited.columns = ['날짜','시간']
new_2018 = pd.concat([df_2018,splited],axis=1)
new_2018 = new_2018.pivot(index='날짜', columns='시간', values='강수량(mm)')

In [ ]:
new_2018

시간,0:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,...,22:00,23:00,2:00,3:00,4:00,5:00,6:00,7:00,8:00,9:00
날짜,,,,,,,,,,,,,,,,,,,,,
2018-01-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2018-01-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-01-10,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0
2018-01-11,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-13,NaN,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.4
2018-12-14,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-12-16,NaN,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2018-12-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0
2018-12-18,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 활동시간(7:00~23:00)에 대한 강수량 합

In [ ]:
df2_2018 = pd.read_csv('2018_2.csv',index_col=0)

In [ ]:
com_2018 = df2_2018.combine_first(new_2018)
com_2018 = com_2018.replace(np.nan, 0)
active_2018 = com_2018[['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00']]
active_2018['sum']=active_2018.sum(axis=1)
active_2018.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)
active_2018 = active_2018.rename(columns={'sum':'act_sum'})
active_2018

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\903939079.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2018['sum']=active_2018.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\903939079.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2018.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)

            act_sum
2018-01-01      0.0
2018-01-02      0.0
2018-01-03      0.0
2018-01-04      0.0
2018-01-05      0.0
...             ...
2018-12-27      0.0
2018-12-28      0.0
2018-12-29      0.0
2018-12-30      0.0
2018-12-31      0.0

[365 rows x 1 columns]

### 출근시간(5:00~10:00)에 대한 강수량 합

In [ ]:
workPre_2018 = com_2018[['5:00','6:00','7:00','8:00','9:00','10:00']]
workPre_2018['sum']=workPre_2018.sum(axis=1)
workPre_2018.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)
workPre_2018 = workPre_2018.rename(columns={'sum':'work_sum'})
workPre_2018

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\3088921111.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2018['sum']=workPre_2018.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\3088921111.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2018.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)

            work_sum
2018-01-01       0.0
2018-01-02       0.0
2018-01-03       0.0
2018-01-04       0.0
2018-01-05       0.0
...              ...
2018-12-27       0.0
2018-12-28       0.0
2018-12-29       0.0
2018-12-30       0.0
2018-12-31       0.0

[365 rows x 1 columns]

### 퇴근시간(16:00~22:00) 강수량에 대한 합

In [ ]:
homePre_2018 = com_2018[['16:00','17:00','18:00','19:00','20:00','21:00','22:00']]
homePre_2018['sum']=homePre_2018.sum(axis=1)
homePre_2018.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)
homePre_2018 = homePre_2018.rename(columns={'sum':'home_sum'})
homePre_2018

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2921380524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2018['sum']=homePre_2018.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2921380524.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2018.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)

            home_sum
2018-01-01       0.0
2018-01-02       0.0
2018-01-03       0.0
2018-01-04       0.0
2018-01-05       0.0
...              ...
2018-12-27       0.0
2018-12-28       0.0
2018-12-29       0.0
2018-12-30       0.0
2018-12-31       0.0

[365 rows x 1 columns]

### 활동/출근/퇴근시간에 따른 강수량의 합 자료 병합

In [ ]:
Pre_2018 = pd.concat([active_2018, workPre_2018], axis=1)
Pre_2018 = pd.concat([Pre_2018, homePre_2018], axis=1)
Pre_2018

            act_sum  work_sum  home_sum
2018-01-01      0.0       0.0       0.0
2018-01-02      0.0       0.0       0.0
2018-01-03      0.0       0.0       0.0
2018-01-04      0.0       0.0       0.0
2018-01-05      0.0       0.0       0.0
...             ...       ...       ...
2018-12-27      0.0       0.0       0.0
2018-12-28      0.0       0.0       0.0
2018-12-29      0.0       0.0       0.0
2018-12-30      0.0       0.0       0.0
2018-12-31      0.0       0.0       0.0

[365 rows x 3 columns]

- 자료 내보내기

In [ ]:
Pre_2018.to_csv('pre2018.csv', index = True, encoding = 'UTF-8')

## 2019년 강수량 데이터

### 시간별 강수량 불러오기 및 변수 가공

In [ ]:
df_2019 = pd.read_csv("2019.csv",encoding='cp949')
df_2019["강수량(mm)"] = df_2019["강수량(mm)"].replace(np.nan, 0)
df_2019.drop(['지점명','지점'], axis=1,  inplace=True)
splited = df_2019['일시'].str.split(' ', expand=True)
splited.columns = ['날짜','시간']
new_2019 = pd.concat([df_2019,splited],axis=1)
new_2019 = new_2019.pivot(index='날짜', columns='시간', values='강수량(mm)')
new_2019

시간,0:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,...,22:00,23:00,2:00,3:00,4:00,5:00,6:00,7:00,8:00,9:00
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-15,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-17,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-21,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-26,NaN,NaN,NaN,0.2,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,1.0,NaN,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,...,NaN,NaN,NaN,0.1,NaN,NaN,0.0,NaN,NaN,0.0
2019-12-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 활동시간(7:00~23:00)에 대한 강수량 합

In [ ]:
df2_2019 = pd.read_csv('2019_2.csv',index_col=0)

In [ ]:
com_2019 = df2_2019.combine_first(new_2019)
com_2019 = com_2019.replace(np.nan, 0)
active_2019 = com_2019[['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00']]
active_2019['sum']=active_2019.sum(axis=1)
active_2019.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)
active_2019 = active_2019.rename(columns={'sum':'act_sum'})
active_2019 = active_2019[0:365]
active_2019

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2283065467.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2019['sum']=active_2019.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2283065467.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2019.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)

            act_sum
2019-01-01      0.0
2019-01-02      0.0
2019-01-03      0.0
2019-01-04      0.0
2019-01-05      0.0
...             ...
2019-12-27      0.0
2019-12-28      0.0
2019-12-29      0.4
2019-12-30      0.3
2019-12-31      0.0

[365 rows x 1 columns]

### 출근시간(5:00~10:00)에 대한 강수량 합

In [ ]:
workPre_2019 = com_2019[['5:00','6:00','7:00','8:00','9:00','10:00']]
workPre_2019['sum']=workPre_2019.sum(axis=1)
workPre_2019.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)
workPre_2019 = workPre_2019.rename(columns={'sum':'work_sum'})
workPre_2019 = workPre_2019[0:365]
workPre_2019

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2996837066.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2019['sum']=workPre_2019.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2996837066.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2019.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)

            work_sum
2019-01-01       0.0
2019-01-02       0.0
2019-01-03       0.0
2019-01-04       0.0
2019-01-05       0.0
...              ...
2019-12-27       0.0
2019-12-28       0.0
2019-12-29       0.0
2019-12-30       0.0
2019-12-31       0.0

[365 rows x 1 columns]

### 퇴근시간(16:00~22:00) 강수량에 대한 합

In [ ]:
homePre_2019 = com_2019[['16:00','17:00','18:00','19:00','20:00','21:00','22:00']]
homePre_2019['sum']=homePre_2019.sum(axis=1)
homePre_2019.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)
homePre_2019 = homePre_2019.rename(columns={'sum':'home_sum'})
homePre_2019 = homePre_2019[0:365]
homePre_2019

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2362647237.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2019['sum']=homePre_2019.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\2362647237.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2019.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)

            home_sum
2019-01-01       0.0
2019-01-02       0.0
2019-01-03       0.0
2019-01-04       0.0
2019-01-05       0.0
...              ...
2019-12-27       0.0
2019-12-28       0.0
2019-12-29       0.4
2019-12-30       0.0
2019-12-31       0.0

[365 rows x 1 columns]

### 활동/출근/퇴근 시간 강수량의 합 자료 병합

In [ ]:
Pre_2019 = pd.concat([active_2019, workPre_2019], axis=1)
Pre_2019 = pd.concat([Pre_2019, homePre_2019], axis=1)
Pre_2019 = Pre_2019.drop(['2019-09-07'])

In [ ]:
Pre_2019.to_csv('pre2019.csv', index = True, encoding = 'UTF-8')

## 2020년 강수량 데이터

### 시간별 강수량 불러오기 및 변수 가공

In [ ]:
df_2020 = pd.read_csv("2020.csv",encoding='cp949')
df_2020["강수량(mm)"] = df_2020["강수량(mm)"].replace(np.nan, 0)
df_2020.drop(['지점명','지점'], axis=1,  inplace=True)
splited = df_2020['일시'].str.split(' ', expand=True)
splited.columns = ['날짜','시간']
new_2020 = pd.concat([df_2020,splited],axis=1)
new_2020 = new_2020.pivot(index='날짜', columns='시간', values='강수량(mm)')
new_2020

시간,0:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,...,22:00,23:00,2:00,3:00,4:00,5:00,6:00,7:00,8:00,9:00
날짜,,,,,,,,,,,,,,,,,,,,,
2020-01-01,0.0,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0
2020-01-06,NaN,NaN,NaN,0.0,NaN,NaN,0.1,NaN,NaN,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,0.6,NaN,NaN,2.4,NaN,NaN,4.6,NaN,NaN,7.2,...,NaN,NaN,NaN,2.1,NaN,NaN,7.4,NaN,NaN,6.5
2020-01-08,7.1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.2,NaN,NaN,4.0,NaN,NaN,1.4
2020-01-19,NaN,NaN,NaN,0.6,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-28,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.3,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-29,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2_2020 = pd.read_csv('2020_2.csv',index_col=0)

### 활동시간(7:00~23:00)에 대한 강수량 합

In [ ]:
com_2020 = df2_2020.combine_first(new_2020)
com_2020 = com_2020.replace(np.nan, 0)
active_2020 = com_2020[['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00']]
active_2020['sum']=active_2020.sum(axis=1)
active_2020.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)
active_2020 = active_2020.rename(columns={'sum':'act_sum'})
active_2020

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\3427458562.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2020['sum']=active_2020.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\3427458562.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2020.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)

            act_sum
2020-01-01      0.1
2020-01-02      0.0
2020-01-03      0.0
2020-01-04      0.0
2020-01-05      0.0
...             ...
2020-12-27      0.0
2020-12-28      0.0
2020-12-29      0.2
2020-12-30      0.0
2020-12-31      0.0

[366 rows x 1 columns]

### 출근시간(5:00~10:00)에 대한 강수량 합

In [ ]:
workPre_2020 = com_2020[['5:00','6:00','7:00','8:00','9:00','10:00']]
workPre_2020['sum']=workPre_2020.sum(axis=1)
workPre_2020.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)
workPre_2020 = workPre_2020.rename(columns={'sum':'work_sum'})
workPre_2020

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\675978011.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2020['sum']=workPre_2020.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\675978011.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2020.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)

            work_sum
2020-01-01       0.0
2020-01-02       0.0
2020-01-03       0.0
2020-01-04       0.0
2020-01-05       0.0
...              ...
2020-12-27       0.0
2020-12-28       0.0
2020-12-29       0.0
2020-12-30       0.0
2020-12-31       0.0

[366 rows x 1 columns]

### 퇴근시간(16:00~22:00) 강수량에 대한 합

In [ ]:
homePre_2020 = com_2020[['16:00','17:00','18:00','19:00','20:00','21:00','22:00']]
homePre_2020['sum']=homePre_2020.sum(axis=1)
homePre_2020.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)
homePre_2020 = homePre_2020.rename(columns={'sum':'home_sum'})
homePre_2020

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\1672446627.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2020['sum']=homePre_2020.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\1672446627.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2020.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)

            home_sum
2020-01-01       0.0
2020-01-02       0.0
2020-01-03       0.0
2020-01-04       0.0
2020-01-05       0.0
...              ...
2020-12-27       0.0
2020-12-28       0.0
2020-12-29       0.0
2020-12-30       0.0
2020-12-31       0.0

[366 rows x 1 columns]

### 활동/출근/퇴근 시간 강수량의 합 자료 병합

In [ ]:
Pre_2020 = pd.concat([active_2020, workPre_2020], axis=1)
Pre_2020 = pd.concat([Pre_2020, homePre_2020], axis=1)
Pre_2020

            act_sum  work_sum  home_sum
2020-01-01      0.1       0.0       0.0
2020-01-02      0.0       0.0       0.0
2020-01-03      0.0       0.0       0.0
2020-01-04      0.0       0.0       0.0
2020-01-05      0.0       0.0       0.0
...             ...       ...       ...
2020-12-27      0.0       0.0       0.0
2020-12-28      0.0       0.0       0.0
2020-12-29      0.2       0.0       0.0
2020-12-30      0.0       0.0       0.0
2020-12-31      0.0       0.0       0.0

[366 rows x 3 columns]

In [ ]:
Pre_2020.to_csv('pre2020.csv', index = True, encoding = 'UTF-8')

## 2021년 강수량 데이터

### 시간별 강수량 불러오기 및 변수 가공

In [ ]:
df_2021 = pd.read_csv("2021.csv",encoding='cp949')
df_2021["강수량(mm)"] = df_2021["강수량(mm)"].replace(np.nan, 0)
df_2021.drop(['지점명','지점'], axis=1,  inplace=True)
splited = df_2021['일시'].str.split(' ', expand=True)
splited.columns = ['날짜','시간']
new_2021 = pd.concat([df_2021,splited],axis=1)
new_2021 = new_2021.pivot(index='날짜', columns='시간', values='강수량(mm)')
new_2021

시간,0:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,...,22:00,23:00,2:00,3:00,4:00,5:00,6:00,7:00,8:00,9:00
날짜,,,,,,,,,,,,,,,,,,,,,
2021-01-05,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0
2021-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-07,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-12,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-13,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN
2021-12-24,NaN,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-27,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.2,NaN,NaN,NaN
2021-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2_2021 = pd.read_csv('2021_2.csv',index_col=0)

### 활동시간(7:00~23:00)에 대한 강수량 합

In [ ]:
com_2021 = df2_2021.combine_first(new_2021)
com_20121 = com_2021.replace(np.nan, 0)
active_2021 = com_2021[['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00']]
active_2021['sum']=active_2021.sum(axis=1)
active_2021.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)
active_2021 = active_2021.rename(columns={'sum':'act_sum'})
active_2021

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\1752051910.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2021['sum']=active_2021.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\1752051910.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  active_2021.drop(['7:00','8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'], axis=1,  inplace=True)

            act_sum
2021-01-01      0.0
2021-01-02      0.0
2021-01-03      0.0
2021-01-04      0.0
2021-01-05      0.0
...             ...
2021-12-27      0.0
2021-12-28      0.0
2021-12-29      0.0
2021-12-30      0.0
2021-12-31      0.0

[365 rows x 1 columns]

### 출근시간(5:00~10:00)에 대한 강수량 합

In [ ]:
workPre_2021 = com_2021[['5:00','6:00','7:00','8:00','9:00','10:00']]
workPre_2021['sum']=workPre_2021.sum(axis=1)
workPre_2021.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)
workPre_2021 = workPre_2021.rename(columns={'sum':'work_sum'})
workPre_2021

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\695551163.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2021['sum']=workPre_2021.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\695551163.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  workPre_2021.drop(['5:00','6:00','7:00','8:00','9:00','10:00'], axis=1,  inplace=True)

            work_sum
2021-01-01       0.0
2021-01-02       0.0
2021-01-03       0.0
2021-01-04       0.0
2021-01-05       0.0
...              ...
2021-12-27       0.0
2021-12-28       0.0
2021-12-29       0.2
2021-12-30       0.0
2021-12-31       0.0

[365 rows x 1 columns]

### 퇴근시간(16:00~22:00) 강수량에 대한 합

In [ ]:
homePre_2021 = com_2021[['16:00','17:00','18:00','19:00','20:00','21:00','22:00']]
homePre_2021['sum']=homePre_2021.sum(axis=1)
homePre_2021.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)
homePre_2021 = homePre_2021.rename(columns={'sum':'home_sum'})
homePre_2021

C:\Users\park0\AppData\Local\Temp\ipykernel_27636\452870509.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2021['sum']=homePre_2021.sum(axis=1)
C:\Users\park0\AppData\Local\Temp\ipykernel_27636\452870509.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homePre_2021.drop(['16:00','17:00','18:00','19:00','20:00','21:00','22:00'], axis=1,  inplace=True)

            home_sum
2021-01-01       0.0
2021-01-02       0.0
2021-01-03       0.0
2021-01-04       0.0
2021-01-05       0.0
...              ...
2021-12-27       0.0
2021-12-28       0.0
2021-12-29       0.0
2021-12-30       0.0
2021-12-31       0.0

[365 rows x 1 columns]

### 활동/출근/퇴근시간 강수량의 합 자료 병합

In [ ]:
Pre_2021 = pd.concat([active_2021, workPre_2021], axis=1)
Pre_2021 = pd.concat([Pre_2021, homePre_2021], axis=1)
Pre_2021

            act_sum  work_sum  home_sum
2021-01-01      0.0       0.0       0.0
2021-01-02      0.0       0.0       0.0
2021-01-03      0.0       0.0       0.0
2021-01-04      0.0       0.0       0.0
2021-01-05      0.0       0.0       0.0
...             ...       ...       ...
2021-12-27      0.0       0.0       0.0
2021-12-28      0.0       0.0       0.0
2021-12-29      0.0       0.2       0.0
2021-12-30      0.0       0.0       0.0
2021-12-31      0.0       0.0       0.0

[365 rows x 3 columns]

In [ ]:
Pre_2021.to_csv('pre2021.csv', index = True, encoding = 'UTF-8')

**다음의 과정으로  만들어진 act_sum(활동시간 강수량), work_sum(출근시간 강수량), home_sum(퇴근시간 강수량)을 변수로 사용하였다.**